# Generated by Django 4.0.5 on 2022-06-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('Name', models.CharField(max_length=200)),
                ('Price', models.FloatField(max_length=200)),
                ('Franchise', models.IntegerField()),
                ('ExtraFranchise', models.IntegerField()),
                ('ServiceType', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
