# Generated by Django 4.0.5 on 2022-06-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packets',
            fields=[
                ('Name', models.CharField(max_length=200)),
                ('MonthlyPayment', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
