# Generated by Django 4.0.5 on 2022-06-16 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_packets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packets_Services',
            fields=[
                ('Id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('IdPackets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packets_fk', to='projects.service')),
                ('IdService', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servico_fk', to='projects.packets')),
            ],
        ),
    ]
