# Generated by Django 4.0.5 on 2022-06-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_packets_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='packetId',
            field=models.ManyToManyField(blank=True, to='projects.packets_services'),
        ),
    ]
