# Generated by Django 4.0.5 on 2022-06-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_service_packetid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='packetId',
        ),
    ]
