# Generated by Django 4.0.5 on 2022-06-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_service_packetid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packets',
            name='MonthlyPayment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='ExtraFranchise',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='Franchise',
            field=models.IntegerField(default=0),
        ),
    ]
