# Generated by Django 4.0.5 on 2022-06-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_service_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='featured_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
